POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBla2thQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MTQxMzU5NDd9.y-XaSV1F-FgJrPJPu9pnxSX33EnJ0TbHjOTfxwqNImQ

{
    "author": "Paavo Pesuska",
    "url": "www.pesublogi.com",
    "title": "Pesublogi",
    "year": 1996
}